#!/bin/bash
set -eu
echo "* Starting the GUILDNET compile process"

# For future use
# echo " Please enter the version you wish to compile.. example: 1.16.2-guildnet"
# read NEAR_VERSION

# Script settings 
  RELEASE=$(lsb_release -c -s)
  NEAR_VERSION=1.16.2-guildnet
  NEAR_REPO="https://github.com/crypto-guys/nearcore.git"
  vm_name="guildnet_compiler"

echo "* Creating the LXC container to build in"
  lxc launch ubuntu:focal ${vm_name}

echo "* Pausing for 60 seconds while the container initializes"
  sleep 30
echo "* 30 more seconds"

echo "* Installing all Required Packages"
  lxc exec ${vm_name} -- /usr/bin/apt-get -qq update
  lxc exec ${vm_name} -- /usr/bin/apt-get -qq upgrade
  lxc exec ${vm_name} -- /usr/bin/apt-get -qq autoremove
  lxc exec ${vm_name} -- /usr/bin/apt-get -qq autoclean
  lxc exec ${vm_name} -- /usr/bin/apt-get -qq install git curl libclang-dev build-essential iperf llvm runc gcc g++ g++-multilib make cmake clang pkg-config libssl-dev libudev-dev libx32stdc++6-7-dbg lib32stdc++6-7-dbg python3-dev
  lxc exec ${vm_name} -- /usr/bin/snap install rustup --classic
  lxc exec ${vm_name} -- /snap/bin/rustup default nightly
  lxc exec ${vm_name} -- /snap/bin/rustup component add clippy-preview
  lxc exec ${vm_name} -- /snap/bin/rustup update
  lxc exec ${vm_name} -- snap install go --classic

echo "* Cloning the github source"
  lxc exec ${vm_name} -- sh -c "rm -rf /tmp/src && mkdir -p /tmp/src/ && git clone $NEAR_REPO /tmp/src/nearcore"

echo "* Switching Version"
  lxc exec ${vm_name} -- sh -c "cd /tmp/src/nearcore && git switch $NEAR_VERSION"

echo "* Attempting to compile"
  lxc exec ${vm_name} -- sh -c "cd /tmp/src/nearcore && make release"

echo "* Creating tarball for easy retrieval"
  lxc exec ${vm_name} -- sh -c "mkdir -p /compressed && cd /tmp/src/nearcore/target/release/ && cp -p genesis-csv-to-json keypair-generator near near-vm-runner-standalone neard state-viewer store-validator /binaries"
  lxc exec ${vm_name} -- sh -c "cd / && tar -cvf nearcore$NEAR_VERSION.tar -C / binaries"

echo "* The nearcore binaries are now in a tarball in the lxc container at /compressed/nearcore1.16.2-guildnet.tar"
  LOCATION=$(pwd)

echo "* Retriving the tarball and storing in $LOCATION/$NEAR_VERSION.tar"
lxc file pull ${vm_name}/binaries/compressed/nearcore1.16.2-guildnet.tar nearcore$NEAR_VERSION.tar
ls /usr/local/src | grep guildnet

echo "* The build of NEARCORE$VERSION has completed."
echo "* This containter has all required software to compile NEARCORE, NODE_EXPORTER, NEAR-EXPORTER, and PROMETHEUS"
