#!/bin/bash
set -eu
echo "* Guildnet Install Script Running"

# Script settings
ACCOUNT_ID=<your_validator_account>
CONFIG_URL="https://s3.us-east-2.amazonaws.com/build.openshards.io/nearcore-deploy/guildnet/config.json"

echo "* Setting up required accounts, groups, and privilages"
adduser --system --disabled-login --disabled-password --ingroup syslog --no-create-home neard-guildnet
groupadd near
usermod -aG syslog neard-guildnet
usermod -aG near neard-guildnet

# Set env variable is not really required unless you use the near-cli on same machine
# export NODE_ENV=guildnet

# Copy Guildnet Files to a suitable location
mkdir -p /var/lib/near/guildnet
tar -xf nearcore1.16.2-guildnet.tar
cd binaries
# Remove the extra folder
rm -rf compressed/
cp * /usr/local/bin

echo '* Getting the correct files and fixing permissions'
neard --home /var/lib/near/guildnet/ --download-genesis --chain-id guildnet --account-id $ACCOUNT_ID
wget $CONFIG_URL -O /var/lib/near/guildnet/config.json
chown -R neard-guildnet:near -R /var/lib/near

echo "* Creating systemd unit file for NEAR validator service"
cat > /lib/systemd/system/neard-guildnet.service <<EOF
[Unit]
Description=NEAR GUILDNET Validator Service
Documentation=https://github.com/nearprotocol/nearcore
Wants=network-online.target
After=network-online.target

[Service]
User=neard-guildnet
Group=near
ExecStart=neard --home /var/lib/near/guildnet run
# Uncomment the below line to log to a file rather than the journal
#StandardOutput=append:/var/log/guildnet.log

[Install]
WantedBy=multi-user.target
EOF

ln -s /lib/systemd/system/near-guildnet-validator.service /etc/systemd/system/multi-user.target.wants/near-guildnet-validator.service

echo '* The installation has completed'

