#cloud-config
hostname: compiler
package_update: true
package_upgrade: true
packages: [curl, wget, git, htop, iperf, nano, python3, python3-dev, python3-pip, libclang-dev, build-essential, llvm, runc, gcc, gcc-9-locales, g++, g++-multilib, make, clang, pkg-config, libssl-dev, libudev-dev, lib32stdc++6-7-dbg, libx32stdc++6-7-dbg, ninja-build, debian-keyring, autoconf, automake, libtool, flex, ttf-bitstream-vera, autoconf-archive, gnu-standards, zip, unzip, gzip, wget, nano, nmap, mlocate, bison, gdb, bzr, ttf-bitstream-vera, autoconf-archive, gnu-standards, libalgorithm-diff-perl, libfakeroot, libffi-dev, libgpgme11, libncurses-dev, libomp5-10, libtinfo-dev, libz3-4, libz3-dev]
preserve_sources_list: true
disable_suites: [$RELEASE-updates, $RELEASE-backports, $RELEASE]
write_files:
  - encoding: b64
    content: IyEvYmluL2Jhc2gNCiMgU2V0dGluZ3MNCnNldCAtZXUNCmVjaG8gJyoqICBTbGVlcCBmb3IgNyBtaW5zIHdoaWxlIHBhY2thZ2VzIGFyZSBpbnN0YWxsZWQgKionDQpzbGVlcCA0MjANCm1rZGlyIC1wIC9zcmMNCmNob3duIC1SIGNyeXB0by1zb2x1dGlvbnM6Y3J5cHRvLXNvbHV0aW9ucyAvc3JjDQp3Z2V0ICJodHRwczovL3N0YXRpYy5ydXN0LWxhbmcub3JnL3J1c3R1cC9kaXN0L3g4Nl82NC11bmtub3duLWxpbnV4LWdudS9ydXN0dXAtaW5pdCINCndnZXQgImh0dHBzOi8vbmVhci1wcm90b2NvbC1wdWJsaWMuczMuY2EtY2VudHJhbC0xLmFtYXpvbmF3cy5jb20vbmVhcmNvcmUtZ2hzYS05M2dxLTM5Y3EtZjczNS1hZHZpc29yeS1maXgtMS56aXAiDQpjaG1vZCAreCBydXN0dXAtaW5pdA0KLi9ydXN0dXAtaW5pdCAtLXF1aWV0IC15IC0tZGVmYXVsdC10b29sY2hhaW4gbmlnaHRseQ0Kc291cmNlIH4vLnByb2ZpbGUgJiYgc291cmNlIH4vLmJhc2hyYw0KcnVzdHVwIHVwZGF0ZQ0KcnVzdHVwIGNvbXBvbmVudCBhZGQgY2xpcHB5LXByZXZpZXcNCnJ1c3R1cCBkZWZhdWx0IG5pZ2h0bHkNCnVuemlwIG5lYXJjb3JlLWdoc2EtOTNncS0zOWNxLWY3MzUtYWR2aXNvcnktZml4LTEuemlwDQpjZCBuZWFyY29yZS1naHNhLTkzZ3EtMzljcS1mNzM1LWFkdmlzb3J5LWZpeC0xDQptYWtlIHJlbGVhc2UNCg==
    owner: root:root
    path: /usr/local/bin/near-compile.sh
    permissions: '0777'
  - encoding: b64
    content: < base 64 encoded sshd_config file >
    owner: root:root
    path: /etc/ssh/sshd_config
    permissions: '0644' 
groups:
  - cloud-users: []
  - docker: []
users:
  - name: crypto-solutions
    gecos: Builder
    Password: "$6$rounds=4096$hashed password"
    no_user_group: false
    homedir: /home/crypto-solutions
    primary_group: crypto-solutions
    sudo: ALL=(ALL) NOPASSWD:ALL
    groups: [users, cloud-users, adm, video, plugdev, dip, netdev]
    shell: /bin/bash
    ssh_authorized_keys:
      - ssh-rsa <goes here>
    inactive: false
    lock_passwd: false 
    uid: 1000 
bootcmd:
  - chown -R crypto-solutions:crypto-solutions /usr/local/share/near-compile.sh
  - su crypto-solutions
  - /usr/local/share/near-compile.sh
